[book]
authors = ["stats-student"]
language = "en"
multilingual = false
src = "src"
title = "Geoffrey documentation"
no-section-label = true
git-repository-url = "https://github.com/stats-student/geoffrey"
git-repository-icon = "fa-github"
